In [1]:
!pip install langchain-openai langchain pdfminer.six chromadb rank_bm25 langchain-community langchain-text-splitters

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: langchain-openai in c:\users\avado\appdata\roaming\python\python313\site-packages (1.6.2)
Requirement already satisfied: langchain in c:\users\avado\appdata\roaming\python\python313\site-packages (1.4.0)
Requirement already satisfied: pdfminer.six in c:\users\avado\appdata\roaming\python\python313\site-packages (20260107)
Requirement already satisfied: chromadb in c:\users\avado\appdata\roaming\python\python313\site-packages (1.5.9)
Requirement already satisfied: rank_bm25 in c:\users\avado\appdata\roaming\python\python313\site-packages (0.2.2)
Requirement already satisfied: langchain-community in c:\users\avado\appdata\roaming\python\python313\site-packages (0.4.2)
Requirement already satisfied: langchain-text-splitters in c:\users\avado\appdata\roaming\python\python313\site-packages (1.1.2)
Requirement already satisfied: certifi>=2024.6.2 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-openai) (2026.2.25)
Requirement already satisfied: langchain-core<2.0.0,>=1.6.2 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-openai) (1.6.3)
Requirement already satisfied: openai<4.0.0,>=2.45.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-openai) (3.13.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-openai) (0.14.0)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain) (1.2.11)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain) (2.12.5)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from pdfminer.six) (3.4.6)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from pdfminer.six) (47.0.0)
Requirement already satisfied: build>=1.0.3 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (1.6.1)
Requirement already satisfied: pydantic-settings>=2.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (2.14.0)
Requirement already satisfied: pybase64>=1.4.1 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (1.5.0)
Requirement already satisfied: uvicorn>=0.18.3 in c:\users\avado\appdata\roaming\python\python313\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.46.0)
Requirement already satisfied: numpy>=1.22.5 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (2.4.4)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (1.30.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (1.44.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (1.44.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (1.44.0)
Requirement already satisfied: tokenizers>=0.13.2 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (0.23.2)
Requirement already satisfied: pypika>=0.48.9 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (1.83.1)
Requirement already satisfied: bcrypt>=4.0.1 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (36.0.3)
Requirement already satisfied: tenacity>=8.2.3 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (5.3.0)
Requirement already satisfied: orjson>=3.9.12 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (3.12.0)
Requirement already satisfied: httpx>=0.27.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (14.3.3)
Requirement already satisfied: jsonschema>=4.19.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from chromadb) (4.26.0)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-community) (3.14.3)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-community) (1.0.8)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-community) (0.12.4)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-community) (2.33.1)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-community) (2.0.52)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\avado\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\avado\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.8.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.5)
Requirement already satisfied: packaging>=24.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from build>=1.0.3->chromadb) (26.0)
Requirement already satisfied: pyproject_hooks in c:\users\avado\appdata\roaming\python\python313\site-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: colorama in c:\users\avado\appdata\roaming\python\python313\site-packages (from build>=1.0.3->chromadb) (0.4.6)
Requirement already satisfied: cffi>=2.0.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from cryptography>=36.0.0->pdfminer.six) (2.0.0)
Requirement already satisfied: anyio in c:\users\avado\appdata\roaming\python\python313\site-packages (from httpx>=0.27.0->chromadb) (4.13.0)
Requirement already satisfied: httpcore==1.* in c:\users\avado\appdata\roaming\python\python313\site-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in c:\users\avado\appdata\roaming\python\python313\site-packages (from httpx>=0.27.0->chromadb) (3.19)
Requirement already satisfied: h11>=0.16 in c:\users\avado\appdata\roaming\python\python313\site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\avado\appdata\roaming\python\python313\site-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\avado\appdata\roaming\python\python313\site-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\avado\appdata\roaming\python\python313\site-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from kubernetes>=28.1.0->chromadb) (1.9.2)
Requirement already satisfied: requests-oauthlib in c:\users\avado\appdata\roaming\python\python313\site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in c:\users\avado\appdata\roaming\python\python313\site-packages (from kubernetes>=28.1.0->chromadb) (2.6.3)
Requirement already satisfied: durationpy>=0.7 in c:\users\avado\appdata\roaming\python\python313\site-packages (from kubernetes>=28.1.0->chromadb) (0.11)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (0.0.19)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langchain-core<2.0.0,>=1.6.2->langchain-openai) (0.17.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (0.4.4)
Requirement already satisfied: xxhash>=3.5.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.0.1)
Requirement already satisfied: distro>=1.7.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (2.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.3.1)
Requirement already satisfied: websockets>=15.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (16.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: flatbuffers in c:\users\avado\appdata\roaming\python\python313\site-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in c:\users\avado\appdata\roaming\python\python313\site-packages (from onnxruntime>=1.14.1->chromadb) (7.34.1)
Requirement already satisfied: jiter<1,>=0.16.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (0.16.0)
Requirement already satisfied: googleapis-common-protos~=1.57 in c:\users\avado\appdata\roaming\python\python313\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.3)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.44.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.44.0)
Requirement already satisfied: opentelemetry-proto==1.44.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.44.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.65b0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.65b0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\avado\appdata\roaming\python\python313\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\avado\appdata\roaming\python\python313\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from rich>=10.11.0->chromadb) (2.20.0)
Requirement already satisfied: greenlet>=1 in c:\users\avado\appdata\roaming\python\python313\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.3.0)
Requirement already satisfied: regex in c:\users\avado\appdata\roaming\python\python313\site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2026.9.10)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in c:\users\avado\appdata\roaming\python\python313\site-packages (from tokenizers>=0.13.2->chromadb) (1.9.0)
Requirement already satisfied: click>=8.2.1 in c:\users\avado\appdata\roaming\python\python313\site-packages (from typer>=0.9.0->chromadb) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\avado\appdata\roaming\python\python313\site-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in c:\users\avado\appdata\roaming\python\python313\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.8.0)
Requirement already satisfied: watchfiles>=0.20 in c:\users\avado\appdata\roaming\python\python313\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.2.0)
Requirement already satisfied: pycparser in c:\users\avado\appdata\roaming\python\python313\site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six) (3.0)
Requirement already satisfied: httpcore2==2.12.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.1.125->langchain-community) (2.12.0)
Requirement already satisfied: truststore>=0.10 in c:\users\avado\appdata\roaming\python\python313\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.1.125->langchain-community) (0.10.4)
Requirement already satisfied: filelock>=3.10.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2026.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\avado\appdata\roaming\python\python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.4.3)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\avado\appdata\roaming\python\python313\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.6.2->langchain-openai) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain) (1.12.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\avado\appdata\roaming\python\python313\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\avado\appdata\roaming\python\python313\site-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import os

try:
    from google.colab import userdata
    os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')
except ImportError:
    pass  # not running in Colab -- assume OPENAI_API_KEY is already set in the environment

from langchain_core.prompts import PromptTemplate
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser
from pdfminer.high_level import extract_text as extract_text_pdf_miner
from langchain_community.vectorstores import Chroma
from langchain_classic.retrievers import EnsembleRetriever
from langchain_community.retrievers import BM25Retriever
from langchain_openai import OpenAIEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_core.runnables import RunnableParallel, RunnablePassthrough

C:\Users\Avado\AppData\Local\Temp\ipykernel_40928\1848288847.py:15: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import Chroma

## Hybrid Search

In [3]:
# Define the directory where the Chroma database will persist data
persist_directory = "/content/hybrid-search"

# Initialize OpenAI embeddings with the specified model
# "text-embedding-3-small" is OpenAI's current, cost-efficient embedding model
embedding = OpenAIEmbeddings(
    model="text-embedding-3-small"
)

In [4]:
def load_data_to_vectordb(file_path,source):
  global bm25_retriever
  # Loop through a list of PDF files to process
  pages = []

  for pdf_name in [file_path]:
      # Open each PDF file in binary mode
      with open(pdf_name, 'rb') as f:
          # Extract text from the PDF using the extract_text_pdf_miner function
          text = extract_text_pdf_miner(f)

          # Clean the extracted text by removing newline characters and joining into a single string
          cleaned_text = " ".join(text.split("\n"))

          # Initialize a list to store document chunks
          docs = []

          # Create a text splitter to divide the text into manageable chunks
          # Each chunk has a maximum size of 2048 characters with a 512-character overlap
          splitter = RecursiveCharacterTextSplitter(chunk_size=2048, chunk_overlap=512)

          # Split the cleaned text into chunks and wrap each chunk in a Document object
          for chunk in splitter.split_text(cleaned_text):
              docs.append(Document(page_content=chunk, metadata={"retrived_from":source,"source": pdf_name}))
              pages.append(Document(page_content=chunk, metadata={"retrived_from":source,"source": pdf_name}))
      # Create a Chroma collection from the processed documents
      # Use the specified persist directory and embedding model for storage and retrieval
      if source == 1:
        bm25_retriever = BM25Retriever.from_documents(pages)
      else:
        db = Chroma.from_documents(
            documents=docs,
            persist_directory=persist_directory,
            embedding=embedding
        )

load_data_to_vectordb(file_path="/content/1706.03762v7.pdf",source=1)
load_data_to_vectordb(file_path="/content/1506.02640v5.pdf",source=2)

In [5]:
# Initialize the BM25 retriever
bm25_retriever.k = 2  # Retrieve top 2 results
print("type of bm25", type(bm25_retriever))

type of bm25 <class 'langchain_community.retrievers.bm25.BM25Retriever'>

In [6]:
# Initialize retriever
docsearch = Chroma(persist_directory=persist_directory, embedding_function=embedding)
retriever_chromadb = docsearch.as_retriever(search_kwargs={"k": 5})

# Initialize the ensemble retriever
ensemble_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, retriever_chromadb], weights=[0.3, 0.7]
)

C:\Users\Avado\AppData\Local\Temp\ipykernel_40928\3235932638.py:2: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the `langchain-chroma package and should be used instead. To use it run `pip install -U `langchain-chroma` and import as `from `langchain_chroma import Chroma``.
  docsearch = Chroma(persist_directory=persist_directory, embedding_function=embedding)

In [7]:
# Example query
query = "What is Self-Attention in Transformers?"

# Retrieve relevant documents/products
docs = ensemble_retriever.invoke(query)

docs

[Document(metadata={'retrived_from': 2, 'source': '/content/1506.02640v5.pdf'}, page_content='features. In Computer vision, 1999. The proceedings of the seventh IEEE international conference on, volume 2, pages 1150–1157. Ieee, 1999. 4  [24] D. Mishkin.  Models accuracy on imagenet 2012 https://github.com/BVLC/caffe/wiki/ val. Models-accuracy-on-ImageNet-2012-val. Ac- cessed: 2015-10-2. 3  [25] C. P. Papageorgiou, M. Oren, and T. Poggio. A general framework for object detection. In Computer vision, 1998. sixth international conference on, pages 555–562. IEEE, 1998. 4  [26] J. Redmon. Darknet: Open source neural networks in c. http://pjreddie.com/darknet/, 2013–2016. 3 [27] J. Redmon and A. Angelova. Real-time grasp detection using convolutional neural networks. CoRR, abs/1412.3128, 2014. 5  [28] S. Ren, K. He, R. Girshick, and J. Sun. Faster r-cnn: To- wards real-time object detection with region proposal net- works. arXiv preprint arXiv:1506.01497, 2015. 5, 6, 7 [29] S. Ren, K. He, R. B. Girshick, X. Zhang, and J. Sun. Object detection networks on convolutional feature maps. CoRR, abs/1504.06066, 2015. 3, 7  [30] O. Russakovsky, J. Deng, H. Su, J. Krause, S. Satheesh, S. Ma, Z. Huang, A. Karpathy, A. Khosla, M. Bernstein, A. C. Berg, and L. Fei-Fei. ImageNet Large Scale Visual Recognition Challenge. International Journal of Computer Vision (IJCV), 2015. 3  [31] M. A. Sadeghi and D. Forsyth. 30hz object detection with In Computer Vision–ECCV 2014, pages 65–79.  dpm v5. Springer, 2014. 5, 6  [32] P. Sermanet, D. Eigen, X. Zhang, M. Mathieu, R. Fergus, and Y. LeCun. Overfeat: Integrated recognition, localiza- tion and detection using convolutional networks. CoRR, abs/1312.6229, 2013. 4, 5  \x0c[33] Z. Shen and X. Xue. Do more dropouts in pool5 feature maps for better object detection. arXiv preprint arXiv:1409.6911, 2014. 7  [34] C. Szegedy, W. Liu, Y. Jia, P. Sermanet, S. Reed, D. Anguelov, D. Erhan, V. Vanhoucke, and A. Rabinovich. Going deeper with convolutions. CoRR, abs/1409.4842, 2014. 2  [35] J. R. Uijlings, K. E. van de Sande, T. Gevers, and A. W. Inter- Smeulders. Selective search for object'),
 Document(metadata={'retrived_from': 2, 'source': '/content/1506.02640v5.pdf'}, page_content='localiza- tion and detection using convolutional networks. CoRR, abs/1312.6229, 2013. 4, 5  \x0c[33] Z. Shen and X. Xue. Do more dropouts in pool5 feature maps for better object detection. arXiv preprint arXiv:1409.6911, 2014. 7  [34] C. Szegedy, W. Liu, Y. Jia, P. Sermanet, S. Reed, D. Anguelov, D. Erhan, V. Vanhoucke, and A. Rabinovich. Going deeper with convolutions. CoRR, abs/1409.4842, 2014. 2  [35] J. R. Uijlings, K. E. van de Sande, T. Gevers, and A. W. Inter- Smeulders. Selective search for object recognition. national journal of computer vision, 104(2):154–171, 2013. 4  [36] P. Viola and M. Jones. Robust real-time object detection. International Journal of Computer Vision, 4:34–47, 2001. 4 [37] P. Viola and M. J. Jones. Robust real-time face detection. International journal of computer vision, 57(2):137–154, 2004. 5  [38] J. Yan, Z. Lei, L. Wen, and S. Z. Li. The fastest deformable part model for object detection. In Computer Vision and Pat- tern Recognition (CVPR), 2014 IEEE Conference on, pages 2497–2504. IEEE, 2014. 5, 6  [39] C. L. Zitnick and P. Doll´ar. Edge boxes: Locating object pro- posals from edges. In Computer Vision–ECCV 2014, pages 391–405. Springer, 2014. 4'),
 Document(metadata={'source': '/content/1506.02640v5.pdf', 'retrived_from': 2}, page_content='want one bounding box predictor to be responsible for each object. We assign one predictor to be “responsible” for predicting an object based on which prediction has the highest current IOU with the ground truth. This leads to specialization between the bounding box predictors. Each predictor gets better at predicting certain sizes, aspect ratios, or classes of object, improving overall recall.  We optimize for sum-squared error in the output of our  During training we optimize the following, multi-part  448448377Conv. Layer7x7x64-s-2Maxpool Layer2x2-s-233112112192335656256Conn. Layer4096Conn. LayerConv. Layer3x3x192Maxpool Layer2x2-s-2Conv. Layers1x1x1283x3x2561x1x2563x3x512Maxpool Layer2x2-s-2332828512Conv. Layers1x1x2563x3x5121x1x5123x3x1024Maxpool Layer2x2-s-23314141024Conv. Layers1x1x5123x3x10243x3x10243x3x1024-s-2337710247710247730} ×4} ×2Conv. Layers3x3x10243x3x1024\x0closs function:  λcoord  S2 (cid:88)  B (cid:88)  i=0  j=0  1obj ij  (xi − ˆxi)2 + (yi − ˆyi)2(cid:105) (cid:104)  + λcoord  S2 (cid:88)  B (cid:88)  i=0  j=0  1obj ij  (cid:20)(cid:16)√  wi −  (cid:17)2  (cid:112)  ˆwi  +  (cid:18)(cid:112)  (cid:19)2(cid:21)  (cid:113)  ˆhi  hi −  +  S2 (cid:88)  B (cid:88)  i=0  j=0  1obj ij  (cid:16)  Ci − ˆCi  (cid:17)2  + λnoobj  S2 (cid:88)  B (cid:88)  i=0  j=0  (cid:16)  1noobj ij  Ci − ˆCi  (cid:17)2  +  S2 (cid:88)  i=0  (cid:88)  1obj i  c∈classes  (pi(c) − ˆpi(c))2  (3)  denotes if object appears in cell i and 1obj  where 1obj ij de- i notes that the jth bounding box predictor in cell i is “re- sponsible” for that prediction.  Note that the loss function only penalizes classiﬁcation error if an object is present in that grid cell (hence the con- ditional class probability discussed earlier). It also only pe- nalizes bounding box coordinate error if that predictor is “responsible” for the ground truth box (i.e. has the highest IOU of any predictor in that grid cell).  We train the network for about 135 epochs on the train- ing and validation data sets from PASCAL VOC 2007 and 2012. When testing on'),
 Document(metadata={'retrived_from': 1, 'source': '/content/1706.03762v7.pdf'}, page_content='identically. This consists of two linear transformations with a ReLU activation in between.  FFN(x) = max(0, xW1 + b1)W2 + b2  (2)  While the linear transformations are the same across different positions, they use different parameters from layer to layer. Another way of describing this is as two convolutions with kernel size 1. The dimensionality of input and output is dmodel = 512, and the inner-layer has dimensionality df f = 2048.  3.4 Embeddings and Softmax  Similarly to other sequence transduction models, we use learned embeddings to convert the input tokens and output tokens to vectors of dimension dmodel. We also use the usual learned linear transfor- mation and softmax function to convert the decoder output to predicted next-token probabilities. In our model, we share the same weight matrix between the two embedding layers and the pre-softmax dmodel. linear transformation, similar to [30]. In the embedding layers, we multiply those weights by  √  5  \x0cTable 1: Maximum path lengths, per-layer complexity and minimum number of sequential operations for different layer types. n is the sequence length, d is the representation dimension, k is the kernel size of convolutions and r the size of the neighborhood in restricted self-attention.  Layer Type  Complexity per Layer  Self-Attention Recurrent Convolutional Self-Attention (restricted)  O(n2 · d) O(n · d2) O(k · n · d2) O(r · n · d)  Sequential Maximum Path Length Operations O(1) O(n) O(1) O(1)  O(1) O(n) O(logk(n)) O(n/r)  3.5 Positional Encoding  Since our model contains no recurrence and no convolution, in order for the model to make use of the order of the sequence, we must inject some information about the relative or absolute position of the tokens in the sequence. To this end, we add "positional encodings" to the input embeddings at the bottoms of the encoder and decoder stacks. The positional encodings have the same dimension dmodel as the embeddings, so that the two can be summed. There are many choices of positional encodings, learned and fixed'),
 Document(metadata={'retrived_from': 1, 'source': '/content/1706.03762v7.pdf'}, page_content='our model contains no recurrence and no convolution, in order for the model to make use of the order of the sequence, we must inject some information about the relative or absolute position of the tokens in the sequence. To this end, we add "positional encodings" to the input embeddings at the bottoms of the encoder and decoder stacks. The positional encodings have the same dimension dmodel as the embeddings, so that the two can be summed. There are many choices of positional encodings, learned and fixed [9].  In this work, we use sine and cosine functions of different frequencies:  P E(pos,2i) = sin(pos/100002i/dmodel) P E(pos,2i+1) = cos(pos/100002i/dmodel)  where pos is the position and i is the dimension. That is, each dimension of the positional encoding corresponds to a sinusoid. The wavelengths form a geometric progression from 2π to 10000 · 2π. We chose this function because we hypothesized it would allow the model to easily learn to attend by relative positions, since for any fixed offset k, P Epos+k can be represented as a linear function of P Epos.  We also experimented with using learned positional embeddings [9] instead, and found that the two versions produced nearly identical results (see Table 3 row (E)). We chose the sinusoidal version because it may allow the model to extrapolate to sequence lengths longer than the ones encountered during training.  4 Why Self-Attention  In this section we compare various aspects of self-attention layers to the recurrent and convolu- tional layers commonly used for mapping one variable-length sequence of symbol representations (x1, ..., xn) to another sequence of equal length (z1, ..., zn), with xi, zi ∈ Rd, such as a hidden layer in a typical sequence transduction encoder or decoder. Motivating our use of self-attention we consider three desiderata.  One is the total computational complexity per layer. Another is the amount of computation that can be parallelized, as measured by the minimum number of sequential operations required.  The third is the path')]

In [8]:
#Extract and print only the page content from each document
import pandas as pd

retrieval_df = pd.DataFrame()

page_content = []
retrieval_source = []
pdf_source = []

for doc in docs:
    page_content.append(doc.page_content)
    retrieval_source.append(doc.metadata['retrived_from'])
    pdf_source.append(doc.metadata['source'])

retrieval_df['page_content'] = page_content
retrieval_df['retrieval_source'] = retrieval_source
retrieval_df['pdf_source'] = pdf_source

retrieval_df.head(10)

,page_content,retrieval_source,pdf_source
0,"features. In Computer vision, 1999. The procee...",2,C:/Users/Avado/AppData/Local/Temp/claude/C--Us...
1,localiza- tion and detection using convolution...,2,C:/Users/Avado/AppData/Local/Temp/claude/C--Us...
2,want one bounding box predictor to be responsi...,2,C:/Users/Avado/AppData/Local/Temp/claude/C--Us...
3,identically. This consists of two linear trans...,1,C:/Users/Avado/AppData/Local/Temp/claude/C--Us...
4,our model contains no recurrence and no convol...,1,C:/Users/Avado/AppData/Local/Temp/claude/C--Us...

## Re Ranking

In [9]:
# Define the directory where the Chroma database will persist data
persist_directory = "/content/re-rank"

# Initialize OpenAI embeddings with the specified model
# "text-embedding-3-small" is OpenAI's current, cost-efficient embedding model
embedding = OpenAIEmbeddings(
    model="text-embedding-3-small"
)

In [10]:
def load_data_to_vectordb(file_path,source):
  # Loop through a list of PDF files to process

  for pdf_name in [file_path]:
      # Open each PDF file in binary mode
      with open(pdf_name, 'rb') as f:
          # Extract text from the PDF using the extract_text_pdf_miner function
          text = extract_text_pdf_miner(f)

          # Clean the extracted text by removing newline characters and joining into a single string
          cleaned_text = " ".join(text.split("\n"))

          # Initialize a list to store document chunks
          docs = []

          # Create a text splitter to divide the text into manageable chunks
          # Each chunk has a maximum size of 2048 characters with a 512-character overlap
          splitter = RecursiveCharacterTextSplitter(chunk_size=2048, chunk_overlap=512)

          # Split the cleaned text into chunks and wrap each chunk in a Document object
          for chunk in splitter.split_text(cleaned_text):
              docs.append(Document(page_content=chunk, metadata={"source": pdf_name}))
      # Create a Chroma collection from the processed documents
      # Use the specified persist directory and embedding model for storage and retrieval

      db = Chroma.from_documents(
            documents=docs,
            persist_directory=persist_directory,
            embedding=embedding
        )

load_data_to_vectordb(file_path="/content/1706.03762v7.pdf",source=1)
load_data_to_vectordb(file_path="/content/1506.02640v5.pdf",source=2)

In [11]:
from langchain_classic.retrievers import ContextualCompressionRetriever
from langchain_classic.retrievers.document_compressors import LLMListwiseRerank

In [12]:
docsearch = Chroma(persist_directory=persist_directory, embedding_function=embedding)

In [13]:
# Initialize an empty DataFrame with specified columns
non_rerank_df = pd.DataFrame(columns=['Text', 'source', 'relevance_score'])

# Perform similarity search using a preconfigured document search tool
# This retrieves the top 3 documents based on relevance to the query
res_docs = docsearch.similarity_search_with_relevance_scores("What is the architecture of transformers?", k=3)

# Loop through the retrieved documents and populate the DataFrame
# (DataFrame._append was removed in pandas 3.x -- pd.concat is the modern, version-safe way to add a row)
for doc in res_docs:
    new_row = pd.DataFrame([{
        'Text': doc[0].page_content,          # Extract the page content (text) from the document
        'source': doc[0].metadata['source'],  # Extract the source metadata
        'relevance_score': doc[1]             # Extract the relevance score
    }])
    non_rerank_df = pd.concat([non_rerank_df, new_row], ignore_index=True)

# Display the first 3 rows of the DataFrame
non_rerank_df.head(3)

,Text,source,relevance_score
0,mechanism instead of sequence- aligned recurre...,C:/Users/Avado/AppData/Local/Temp/claude/C--Us...,0.340344
1,mechanism instead of sequence- aligned recurre...,C:/Users/Avado/AppData/Local/Temp/claude/C--Us...,0.340344
2,global dependencies between input and output. ...,C:/Users/Avado/AppData/Local/Temp/claude/C--Us...,0.286772

In [14]:
# Import and initialize the reranker for document compression
# OpenAI does not offer a standalone hosted rerank endpoint like Cohere's CohereRerank,
# so LLMListwiseRerank is used instead: it reranks candidate documents by asking a chat
# model (here, gpt-4o-mini) to directly judge and reorder them by relevance -- the same
# core idea as RankGPT.
compressor = LLMListwiseRerank.from_llm(llm=ChatOpenAI(model="gpt-4o-mini", temperature=0), top_n=3)
# LLMListwiseRerank is a document compressor that uses an LLM to rerank documents by relevance.

# Create a ContextualCompressionRetriever for improved document retrieval
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor,               # Use the reranker as the base compression mechanism
    base_retriever=docsearch.as_retriever()   # Use the existing document search tool as the base retriever
)
# The ContextualCompressionRetriever combines the base retriever's results with reranking
# to provide more contextually relevant and concise results.

In [15]:
# Initialize an empty DataFrame with specified columns
source_df = pd.DataFrame(columns=['Text', 'source', 'rerank_position'])

# Retrieve compressed (reranked) documents relevant to the query using the contextual compression retriever
compressed_docs = compression_retriever.invoke("What is the architecture of Transformers?")

# Loop through the reranked documents and populate the DataFrame
# (DataFrame._append was removed in pandas 3.x -- pd.concat is the modern, version-safe way to add a row)
for i, doc in enumerate(compressed_docs):
    new_row = pd.DataFrame([{
        'Text': doc.page_content,          # Extract the content of the document
        'source': doc.metadata['source'],   # Extract the source information
        'rerank_position': i + 1            # LLMListwiseRerank returns documents already in relevance order (1 = most relevant)
    }])
    source_df = pd.concat([source_df, new_row], ignore_index=True)

# Display the first 3 rows of the DataFrame
source_df.head(3)

,Text,source,rerank_position
0,mechanism instead of sequence- aligned recurre...,C:/Users/Avado/AppData/Local/Temp/claude/C--Us...,1
1,mechanism instead of sequence- aligned recurre...,C:/Users/Avado/AppData/Local/Temp/claude/C--Us...,2
2,global dependencies between input and output. ...,C:/Users/Avado/AppData/Local/Temp/claude/C--Us...,3

We can see the last result is different and the relevance scores are also different but they are according to the relevance model